### PR TITLE
Publish dist folder

### PR DESCRIPTION
**Pull request by angelo-moreira**
add build folder so we don't have to publish to npm.
If someone thinks this is not the right way please lmk.

### CODE REVIEW

**Comment by varbrad** [comment]
What exactly is the purpose of all this stuff? Is this repo not the subgraph server itself?

If so - you surely only want to run this `build`/`bundle` of TS -> JS within the docker image, and then run the JS entrypoint from the docker image?

Or are you importing this repository in another repository somewhere?

**Comment by varbrad** [comment]
Oh wait you've forked the TypeGraphQL project here?

How are you consuming it within the subgraph?

**Comment by angelo-moreira** [comment]
> What exactly is the purpose of all this stuff? Is this repo not the subgraph server itself?

No, this is a fork on Type GraphQL, the draft for v2

> Or are you importing this repository in another repository somewhere?

yes, this library gets imported in the Subgraph

**Comment by angelo-moreira** [comment]
> Oh wait you've forked the TypeGraphQL project here?

Yes the draft PR that's been working on

> How are you consuming it within the subgraph?

I am importing it here, if you're happy with this then you can next review this https://github.com/WithWise/acc-subgraph-frontend/pull/12

**Comment by angelo-moreira** [comment]
Closing this PR as #2 fixes it without having to publish dirty dist folders 😄

**Pull request closed without merging**
